[package]
name = "turto"
version = "0.1.2"
edition = "2021"
authors = ["phoxwupsh"]
rust-version = "1.70"
license = "MIT"
repository = "https://github.com/phoxwupsh/turto"
description = "turto is a simple and easy-to-use Discord music bot that supports customization."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = "2.3.1"
serde = "1.0.188"
serde_json = "1.0.107"
regex = "1.9.3"
toml = "0.8.0"
rand = "0.8.5"
sha256 = "1.4.0"

[dependencies.serenity]
version = "0.11.6"
features = ["client", "standard_framework", "voice", "rustls_backend", "collector"]

[dependencies.tokio]
version = "1.32.0"
features = ["macros", "rt-multi-thread", "signal"]

[dependencies.songbird]
version = "0.3.2"
features = ["yt-dlp"]

[dependencies.dashmap]
version = "5.5.3"
features = ["serde"]

[profile.release]
opt-level = 3
lto = true
strip = true
