[package]
name = "turto-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
url = "2.3.1"
serde = "1.0.163"
serde_json = "1.0.96"
lazy_static = "1.4.0"
regex = "1.9.3"

[dependencies.serenity]
version = "0.11.5"
features = ["client", "standard_framework", "voice", "rustls_backend", "collector"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread", "signal"]

[dependencies.songbird]
version = "0.3.2"
features = ["yt-dlp"]

[profile.release]
opt-level = 3
lto = true
