# Below are arguments that would appear in the messages, arguments must be wrapped by curly brackets "{" and "}"
# If you really need curly brackets "{" or "}" to appear in your message, place a backslash before it
# In toml the text wrapped by double quotation marks escape the backslashes, so you need two backslashes
# Or, you can use single quotation marks to wrap you text, and you won't need two backslashes
# You can refer to https://toml.io/en/v1.0.0 for more details
# "bot_voice_channel" is the voice channel that the bot is currently staying/joining/leaving, represented by mentioning
# "title" is the title of the item that is being played/paused/stopped
# "url" is the url that provided by the users
# "volume" is the volume being set, represented by number emojis, ranging from 0 to 100
# "autoleave_status" is the status of autoleave, can be on or off, represented by emojis
# "playlist_length" is the length of the guild's playlist
# "length" is the length of the item that is currently being played
# "seek_limit" is the duration limitation of seeking, corresponding to the value with same name in config.toml
# "user" is the user that is being banned/unbanned, represented by mentioning
# "command_name" is the name of commands that is querying
not_playing = "Not playing now."
user_not_in_voice_channel = "You are not in a voice channel."
bot_not_in_voice_channel = "turto is not in a voice channel."
different_voice_channel = "You are not in {bot_voice_channel}"
play = "▶️ {title}"
pause = "⏸️ {title}"
skip = "⏭️ {title}"
stop = "⏹️ {title}"
join = "{voice_channel}⬅️🐢"
leave = "⬅️🐢{voice_channel}"
queue = "✅ {title}"
remove = "❎ {title}"
remove_all = "The playlist has been cleared."
invalid_remove = "Please enter a positive number to remove one, or a range to remove multiple, or `all` to clear the playlist."
invalid_remove_index = "Please enter a number or range between 1 and {playlist_length}."
url_not_found = "Can't find `{url}`"
invalid_url = "Please provide a valid url."
volume = "🔊{volume}"
invalid_volume = "Enter a number ranges from 0 to 100."
toggle_autoleave = "Autoleave: {autoleave_status}"
invalid_autoleave = "Please specify whether to turn on or off autoleave."
invalid_seek = "Please enter a number between 0 and the seek limitation {seek_limit}."
seek_not_allow = "Seeking is not allow."
backward_seek_not_allow = "Backward seeking is not allowed."
seek_not_long_enough = "`{title}` is only {length} seconds long."
administrator_only = "This command can only be invoked by an adminstrator."
user_got_banned = "{user} has been banned."
user_already_banned = "{user} had already been banned."
user_got_unbanned = "{user} has been unbanned."
user_not_banned = "{user} hasn't been banned yet."
banned_user_repsonse = "You are not allow to invoke any command because you are banned."
invalid_user = "Please specify a user by mentioning."
help = "Here are all the available commands, you can use the menu below to see detailed usage for each command. Remember to prefix any command with an exclamation mark (`!`)."
command_help = "Here is how to use `{command_name}`. Remember to prefix any command with an exclamation mark (`!`)."